---
title: "Causal Inference with Missing Treatments"
author: "Joon Sup Park"
date: "2023-01-29"
output: pdf_document
---

```{r setup, message=F, warning=F, echo=F}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(glm2)
library(PSweight)
library(mvtnorm)
library(rje)
library(reshape2)
library(gridExtra)

library(factoextra)
```

```{r}
generate_data <- function(n,p){
  W_mean = rep(0, p)
  W_var = 5*diag(p)
  W = rmvnorm(n = n, mean = W_mean, sigma = W_var)
  return(W)
}

get_true_treatment <- function(W,n){
  theta = rep(c(-1, 0.5, -0.25, -0.1),dim(W)[2]/4)
  pi = expit(W %*% theta)
  Z = rbernoulli(n = n, p = pi)
  return (Z)
}

get_true_outcome <- function(n,W,Z){
  ATE_true = 20
  # /4 is because we consider dimensions of W as multiples of 4
  beta = c(210, rep(c(27.4, 13.7, 13.7, 13.7), dim(W)[2]/4), ATE_true)
  eps = rnorm(n = n, mean = 0, sd = 1)
  y = cbind(rep(1, n), W, Z) %*% beta + eps
  return (y)
}
```

```{r}
set.seed(1652)

n <- 100000
p <- 4

W <- generate_data(n, p)
Z <- get_true_treatment(W, n)
y <- get_true_outcome(n, W, Z)
```

```{r}
W_df <- data.frame(W)
W_df <- scale(W_df)
 
# output to be present as PNG file
#png(file = "KMeansExample2.png")
 
km <- kmeans(W_df, centers = 10000, nstart = 25)
 
# Visualize the clusters
#fviz_cluster(km, data = W_df)
 
# saving the file
#dev.off()
```


```{r}
df_y <- data.frame(cbind(y, km$cluster))

ATE_by_cluster <- cbind(rep(0, 10000), rep(0, 10000))

for (k in 1:10000){
  if (nrow(df_y[df_y[,2] == k,]) > 2){
    km_y_temp <- kmeans(df_y[df_y[,2] == k,], centers = 2, nstart = 25)

    df_y_temp <- data.frame(cbind(df_y[df_y[,2] == k,], km_y_temp$cluster))
    mean_y_temp_1 <- mean(df_y_temp$X1[df_y_temp$km_y_temp.cluster == 1])
    mean_y_temp_2 <- mean(df_y_temp$X1[df_y_temp$km_y_temp.cluster == 2])
    ATE_by_cluster[k,1] <- mean_y_temp_1 - mean_y_temp_2 
    ATE_by_cluster[k,2] <- nrow(df_y[df_y[,2] == k,])
  }
}

```

```{r}
df_ATE_by_cluster <- data.frame(ATE_by_cluster)

sum(abs(df_ATE_by_cluster$X1)*df_ATE_by_cluster$X2)/sum(df_ATE_by_cluster$X2)

```






```{r}
df_y <- data.frame(cbind(y, km$cluster))

km_y_1 <- kmeans(df_y[df_y[,2] == 1,], centers = 2, nstart = 25)
df_y[df_y[,2] == 1,]
km_y_1$cluster

df_y_1 <- data.frame(cbind(df_y[df_y[,2] == 1,], km_y_1$cluster))
mean_y_1_1 <- mean(df_y_1$X1[df_y_1$km_y_1.cluster == 1])
mean_y_1_2 <- mean(df_y_1$X1[df_y_1$km_y_1.cluster == 2])
mean_y_1_1 - mean_y_1_2
```

```{r}
km_y_2 <- kmeans(df_y[df_y[,2] == 2,], centers = 2, nstart = 25)
df_y[df_y[,2] == 2,]
km_y_2$cluster

df_y_2 <- data.frame(cbind(df_y[df_y[,2] == 2,], km_y_2$cluster))
mean_y_2_1 <- mean(df_y_2$X1[df_y_2$km_y_2.cluster == 1])
mean_y_2_2 <- mean(df_y_2$X1[df_y_2$km_y_2.cluster == 2])
mean_y_2_1 - mean_y_2_2
```

```{r}
km_y_3 <- kmeans(df_y[df_y[,2] == 3,], centers = 2, nstart = 25)

df_y_3 <- data.frame(cbind(df_y[df_y[,2] == 3,], km_y_3$cluster))
mean_y_3_1 <- mean(df_y_3$X1[df_y_3$km_y_3.cluster == 1])
mean_y_3_2 <- mean(df_y_3$X1[df_y_3$km_y_3.cluster == 2])
mean_y_3_1 - mean_y_3_2
```
